/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.intsuperior.vista;

import ec.edu.intsuperior.controlador.Controlador;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;



/**
 *
 * @author quish
 */
public class Administrador extends javax.swing.JFrame {
    
    Controlador controlador;
    
    /**
     * Creates new form Administrador
     */
    public Administrador(Controlador controlador) {
        this.controlador=controlador;
        this.setExtendedState(6);
        
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jpInicioAdmin = new FondoPanel();
        lbAdmin = new javax.swing.JLabel();
        btCerrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbInicio = new javax.swing.JMenu();
        miAyuda = new javax.swing.JMenuItem();
        miAcercaDe = new javax.swing.JMenuItem();
        mbEmpleado = new javax.swing.JMenu();
        mtmActualizar = new javax.swing.JMenuItem();
        mbCliente = new javax.swing.JMenu();
        mtmActualizarCli = new javax.swing.JMenuItem();
        mbCabana = new javax.swing.JMenu();
        mtmCab = new javax.swing.JMenuItem();
        mbServicio = new javax.swing.JMenu();
        mbReserva = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpInicioAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbAdmin.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        lbAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAdmin.setText("INICIO COMO ADMINISTRADOR");
        lbAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbAdmin.setOpaque(true);
        jpInicioAdmin.add(lbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, 27));

        btCerrar.setText("CERRAR");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });
        jpInicioAdmin.add(btCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, -1, -1));

        escritorio.add(jpInicioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 853, 434));

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 0));

        mbInicio.setText("Inicio");

        miAyuda.setText("Ayuda");
        miAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAyudaActionPerformed(evt);
            }
        });
        mbInicio.add(miAyuda);

        miAcercaDe.setText("Acerca de");
        miAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAcercaDeActionPerformed(evt);
            }
        });
        mbInicio.add(miAcercaDe);

        jMenuBar1.add(mbInicio);

        mbEmpleado.setText("Empleado");
        mbEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbEmpleadoActionPerformed(evt);
            }
        });

        mtmActualizar.setText("Actualizar Empleado");
        mtmActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtmActualizarActionPerformed(evt);
            }
        });
        mbEmpleado.add(mtmActualizar);

        jMenuBar1.add(mbEmpleado);

        mbCliente.setText("Cliente");

        mtmActualizarCli.setText("Actualizar Cliente");
        mtmActualizarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtmActualizarCliActionPerformed(evt);
            }
        });
        mbCliente.add(mtmActualizarCli);

        jMenuBar1.add(mbCliente);

        mbCabana.setText("Cabañas");

        mtmCab.setText("Actualizar informacion");
        mtmCab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtmCabActionPerformed(evt);
            }
        });
        mbCabana.add(mtmCab);

        jMenuBar1.add(mbCabana);

        mbServicio.setText("Servicios");
        jMenuBar1.add(mbServicio);

        mbReserva.setText("Reservas");
        jMenuBar1.add(mbReserva);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAyudaActionPerformed
        controlador.openJPFAyuda();
    }//GEN-LAST:event_miAyudaActionPerformed

    private void miAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAcercaDeActionPerformed
        controlador.openJPFAcercaDe();
    }//GEN-LAST:event_miAcercaDeActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
        controlador.closeAdministrador();
        controlador.showLoggin();
    }//GEN-LAST:event_btCerrarActionPerformed

    private void mbEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbEmpleadoActionPerformed
        
    }//GEN-LAST:event_mbEmpleadoActionPerformed

    private void mtmActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtmActualizarActionPerformed
        controlador.showEmpleado();
    }//GEN-LAST:event_mtmActualizarActionPerformed

    private void mtmActualizarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtmActualizarCliActionPerformed
        controlador.showClientes();
    }//GEN-LAST:event_mtmActualizarCliActionPerformed

    private void mtmCabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtmCabActionPerformed
        
    }//GEN-LAST:event_mtmCabActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Administrador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCerrar;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jpInicioAdmin;
    private javax.swing.JLabel lbAdmin;
    private javax.swing.JMenu mbCabana;
    private javax.swing.JMenu mbCliente;
    private javax.swing.JMenu mbEmpleado;
    private javax.swing.JMenu mbInicio;
    private javax.swing.JMenu mbReserva;
    private javax.swing.JMenu mbServicio;
    private javax.swing.JMenuItem miAcercaDe;
    private javax.swing.JMenuItem miAyuda;
    private javax.swing.JMenuItem mtmActualizar;
    private javax.swing.JMenuItem mtmActualizarCli;
    private javax.swing.JMenuItem mtmCab;
    // End of variables declaration//GEN-END:variables

  class FondoPanel extends JPanel{
        private Image imagen;
        
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Imag/caba (4).jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            //setOpaque(false);
            
            super.paint(g);
           
        }
    }
}
