package ec.edu.intsuperior.vista;

import ec.edu.intsuperior.controlador.Controlador;


public class JPFAyuda extends javax.swing.JPanel {
    
    Controlador controlador;
    
   
    public JPFAyuda(Controlador controlador) {
        this.controlador = controlador;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAyuda = new javax.swing.JLabel();

        lbAyuda.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 36)); // NOI18N
        lbAyuda.setText("CENTRO DE AYUDA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lbAyuda)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lbAyuda)
                .addContainerGap(208, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAyuda;
    // End of variables declaration//GEN-END:variables
}